name: Upload to S3

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      S3_BUCKET_URL: s3://swiswiswift.com
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::071766756112:role/swiswiswift-github-actions
          aws-region: ap-northeast-1
      - name: Install Hugo
        run: |
          wget -q https://github.com/gohugoio/hugo/releases/download/v0.128.2/hugo_extended_0.128.2_linux-amd64.deb
          sudo dpkg -i hugo_extended_0.128.2_linux-amd64.deb
      - name: Build Files
        run: make build
      - name: Upload to S3
        run: |
          aws s3 sync ./hugo/public $S3_BUCKET_URL --exact-timestamps --delete
